version: '3'

networks:
  proxy:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.5.0
    networks:
      - proxy
    volumes:
      - "/srv/prometheus:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    labels:
      traefik.backend: "prometheus"
      traefik.port: 9090
      traefik.frontend.rule: "Host:prometheus.srv.lair.doismellburning.co.uk"
    user: 108:112 # prometheus:prometheus on host - hardcoding of sadness :( - see https://github.com/prometheus/prometheus/issues/3441
