version: '3'

networks:
  proxy:
    external: true

services:
  homeassistant:
    image: homeassistant/home-assistant:2022.5.5
    networks:
      - proxy
    volumes:
      - "/srv/git/homeassistant-config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123
      traefik.http.routers.homeassistant.rule: Host(`hass.srv.lair.doismellburning.co.uk`)
