version: '3'

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:1.7.7
    networks:
      - proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    command: traefik --docker
    labels:
      traefik.frontend.rule: "Host:traefik.srv.lair.doismellburning.co.uk"
      traefik.port: 8080
