version: '3'

networks:
  proxy:
    external: true

volumes:
  grafana-storage:
    external: true

services:
  grafana:
    image: grafana/grafana:7.3.5
    networks:
      - proxy
    volumes:
      - "grafana-storage:/var/lib/grafana"
    labels:
      traefik.http.routers.grafana.rule: Host(`grafana.srv.lair.doismellburning.co.uk`)
