version: '3'

networks:
  proxy:
    external: true

services:
  grafana:
    image: grafana/grafana:4.6.5
    networks:
      - proxy
    labels:
      traefik.backend: "grafana"
      traefik.port: 3000
      traefik.frontend.rule: "Host:grafana.srv.lair.doismellburning.co.uk"
