version: '3'

services:
  imapfilter:
    build:
      context: .
    image: doismellburning/imapfilter
    volumes:
      - ./imapfilter-doismellburning:/opt/doismellburning/imapfilter
    command: /opt/doismellburning/imapfilter/loop
