version: '3'

networks:
  proxy:
    external: true

services:
  smokeping:
    image: linuxserver/smokeping:131
    networks:
      - proxy
    volumes:
      - "./config:/config:ro" # ro because the image tries to write there and "fix" permissions and other sadness
    labels:
      traefik.http.routers.smokeping.rule: Host(`smokeping.srv.lair.doismellburning.co.uk`)
